name: Build Releases

on:
  workflow_dispatch:
  push:
    'tags':
      - 'v*'

env:
  GITHUB_REF: ${{ github.ref }}
  GO_VERSION: '1.21.3'

jobs:
  build-linux-arm64:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          repository: gregtwallace/goracadm
          ref: ${{ env.GITHUB_REF }}
          fetch-depth: 0

      - name: Update apt
        run: sudo apt update

      - name: Install cross-compiler for linux/arm64
        run: sudo apt-get -y install gcc-aarch64-linux-gnu

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '${{ env.GO_VERSION }}'

      - name: Build
        run: go build -o ./goracadm-linux-arm64 -v ./
        env:
          GOOS: linux
          GOARCH: arm64
          CC: aarch64-linux-gnu-gcc

      - name: Save Compiled Binary
        uses: actions/upload-artifact@v3
        with:
          name: goracadm-linux-arm64
          path: ./goracadm-linux-arm64

  build-linux-amd64:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Backend Repo
        uses: actions/checkout@v3
        with:
          repository: gregtwallace/goracadm
          ref: ${{ env.GITHUB_REF }}
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '${{ env.GO_VERSION }}'

      - name: Build
        run: go build -o ./goracadm-linux-amd64 -v ./
        env:
          GOOS: linux
          GOARCH: amd64

      - name: Save Compiled Binary
        uses: actions/upload-artifact@v3
        with:
          name: goracadm-linux-amd64
          path: ./goracadm-linux-amd64

  build-windows-amd64:
    runs-on: windows-latest
    steps:
      - name: Checkout Backend Repo
        uses: actions/checkout@v3
        with:
          repository: gregtwallace/goracadm
          ref: ${{ env.GITHUB_REF }}
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '${{ env.GO_VERSION }}'

      - name: Build
        run: go build -o ./goracadm-windows-amd64.exe -v ./
        env:
          GOOS: windows
          GOARCH: amd64

      - name: Save Compiled Binary
        uses: actions/upload-artifact@v3
        with:
          name: goracadm-windows-amd64
          path: ./goracadm-windows-amd64.exe
